title: Statistical Physics and Machine Learning
description: PSL Weeks Advanced Lecture Course
baseurl: "/statphysml-psl-week"
url: "https://brloureiro.github.io"

markdown: kramdown

plugins:
  - jekyll-feed
